apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: monetics
  description: Sistema de gestão financeira pessoal
  tags:
    - finance
    - personal-finance
spec:
  owner: infra
  domain: fictorpay

---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: monetics-api
  title: monetics-api
  description: API RESTful para gestão financeira pessoal - Controle de contas, categorias, transações e orçamentos
  annotations:
    github.com/project-slug: alpheres/monetics
    backstage.io/techdocs-ref: dir:.
  tags:
    - golang
    - api
  links:
    - url: https://github.com/alpheres/monetics
      title: Repositório GitHub
      icon: github
    - url: http://localhost:8080/swagger/index.html
      title: API Documentation (Swagger)
      icon: docs
spec:
  type: service
  lifecycle: production
  owner: infra
  system: monetics
  providesApis:
    - monetics-api-v1
  dependsOn:
    - resource:default/monetics-database

---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: monetics-api-v1
  title: Monetics API v1
  description: API REST para gestão financeira pessoal com autenticação, contas, transações e orçamentos
  annotations:
    github.com/project-slug: alpheres/monetics
  tags:
    - golang
    - api
    - rest
    - openapi
spec:
  type: openapi
  lifecycle: production
  owner: infra
  system: monetics
  definition:
    $text: ./docs/openapi/swagger.yaml

---
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: monetics-database
  title: Monetics PostgreSQL Database
  description: Banco de dados principal do Monetics - armazena usuários, contas, transações, categorias e orçamentos
  tags:
    - postgresql
    - database
spec:
  type: database
  owner: infra
  system: monetics
