apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: monetics-api
  title: Monetics API
  description: API RESTful para gestão financeira pessoal - Controle de contas, categorias, transações e orçamentos
  annotations:
    github.com/project-slug: edalferes/monetics
    backstage.io/techdocs-ref: dir:.
  tags:
    - golang
    - api
    - backend
    - rest
    - finance
    - budget
    - personal-finance
  links:
    - url: https://github.com/edalferes/monetics
      title: Repositório GitHub
      icon: github
    - url: http://localhost:8080/swagger/index.html
      title: API Documentation (Swagger)
      icon: docs
spec:
  type: service
  lifecycle: production
  owner: group:default/finance-team
  system: monetics
  providesApis:
    - monetics-api-v1
  dependsOn:
    - resource:default/monetics-database

---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: monetics-api-v1
  title: Monetics API v1
  description: API REST para gestão financeira pessoal com autenticação, contas, transações e orçamentos
  tags:
    - rest
    - openapi
    - finance
spec:
  type: openapi
  lifecycle: production
  owner: group:default/finance-team
  system: monetics
  definition: |
    openapi: 3.0.0
    info:
      title: Monetics Financial Management API
      version: 1.0.0
      description: API para gestão financeira pessoal
    paths:
      /health:
        get:
          summary: Health check
          responses:
            '200':
              description: Service is healthy
      /v1/auth/login:
        post:
          summary: User authentication
          responses:
            '200':
              description: Login successful
      /v1/auth/users:
        get:
          summary: List users
          responses:
            '200':
              description: Users retrieved
        post:
          summary: Create user
          responses:
            '201':
              description: User created
      /v1/budget/accounts:
        get:
          summary: List accounts
          responses:
            '200':
              description: Accounts retrieved
        post:
          summary: Create account
          responses:
            '201':
              description: Account created
      /v1/budget/categories:
        get:
          summary: List categories
          responses:
            '200':
              description: Categories retrieved
        post:
          summary: Create category
          responses:
            '201':
              description: Category created
      /v1/budget/transactions:
        get:
          summary: List transactions
          responses:
            '200':
              description: Transactions retrieved
        post:
          summary: Create transaction
          responses:
            '201':
              description: Transaction created
      /v1/budget/budgets:
        get:
          summary: List budgets
          responses:
            '200':
              description: Budgets retrieved
        post:
          summary: Create budget
          responses:
            '201':
              description: Budget created
      /v1/budget/reports/monthly:
        get:
          summary: Get monthly financial report
          responses:
            '200':
              description: Report retrieved

---
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: monetics-database
  title: Monetics PostgreSQL Database
  description: Banco de dados principal do Monetics - armazena usuários, contas, transações, categorias e orçamentos
  tags:
    - postgresql
    - database
    - finance
spec:
  type: database
  owner: group:default/finance-team
  system: monetics
