name: PR Check

on:
  pull_request:
    branches: [main, develop]

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v4
        with:
          go-version: '1.25.1'
      
      - name: Format check
        run: |
          if [ "$(gofmt -l . | wc -l)" -gt 0 ]; then
            echo "Code needs formatting. Run: gofmt -w ."
            exit 1
          fi
      
      - name: Tests
        run: go test ./...
      
      - name: Build
        run: go build ./...